### ISSUE TITLE
Offtopic question

### ISSUE THREAD

**Issue by net4u** [beyourmarket/beyourmarket#11]
Hi,

What is your (simple or) best approach when it comes about View(s) that concerns multiple models? I have in mind especially the case when with have master/details situations. The first that it comes in my mind is for example AspNetUsers that can have several child (.e.g. OperationJournal, Orders, Invoices etc.)
I use ViewModel and partial views but sometimes is painful. I have results with Models that are not (directly) in relation, but for example now I struggle to render the current user profile information and also all is related to it from several tables.

**Comment by beyourmarket** [comment]
Hi,

  I think it depends on how your user interface looks, which your view model based on. Generally, I would keep UI simple with least number of models as possible. If it's many view models, it means the UI could be sophisticated to users. One way is instead of having one view with many models, you could break it down into separate views and it would also be easier to maintain and extend.

**Comment by net4u** [comment]
Hi,

For example in this case is about a kind of dashboard. Anyway is not about to be cluttered, nobody likes this, but there are scenarios when you need to put data together in one screen. At detail level, I try as possible to use partial views, but sometimes is confusing to do it.

**Comment by beyourmarket** [comment]
right, in that case like dashboard, the model would be an aggregated model (which are not directly mapped to tables in database), where your controller would be then responsible to get data from different places and aggregate them in the model.
