### ISSUE TITLE
Price unit Label validation

### ISSUE THREAD

**Issue by marksarcade** [beyourmarket/beyourmarket#18]
Hey there,

Picked up a minor issue with the Price Unit Label on creating a new Listing. I tried to populate it with the value "On-completion" which was not valid (too long I think).

Just needs a minor change to the validation rules for the field?

**Comment by kenyeung128** [comment]
Hi @marksarcade , you are right, it's because the Price Unit Label is defined with length=10, apparently it might be a bit short, I just extended it with length=20.

To upgrade your database table automatically after getting latest code, you just need to set MigrateDatabaseToLatest = true in the web.config

<add key="MigrateDatabaseToLatestVersion" value="true"/>
